# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2025-02-20 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessing_water_quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.CharField(max_length=3000)),
                ('State', models.CharField(max_length=3000)),
                ('District_Name', models.CharField(max_length=3000)),
                ('Place_Name', models.CharField(max_length=3000)),
                ('ph', models.CharField(max_length=3000)),
                ('Hardness', models.CharField(max_length=3000)),
                ('Solids', models.CharField(max_length=3000)),
                ('Chloramines', models.CharField(max_length=3000)),
                ('Sulfate', models.CharField(max_length=3000)),
                ('Conductivity', models.CharField(max_length=3000)),
                ('Organic_carbon', models.CharField(max_length=3000)),
                ('Trihalomethanes', models.CharField(max_length=3000)),
                ('Turbidity', models.CharField(max_length=3000)),
                ('Prediction', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(default='Unknown', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
