# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2025-02-20 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0008_auto_20250220_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(default='Unknown', max_length=3000),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=300),
        ),
    ]
