# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2025-02-20 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0009_auto_20250220_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='gender',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
